mantenimientos/urls.py
from django.conf.urls import patterns, include, url

from mantenimientos.views import *

from django.contrib.auth.decorators import permission_required

urlpatterns = [

	# Views
	url(r'^mantenimiento/$', MantenimientoListView.as_view(), name='mantenimiento_lis'),
	url(r'^mantenimientoaprobado/$', MantenimientoAprobadoListView.as_view(), name='mantenimiento_aprobado_lis'),

	url(r'^mantenimiento/(?P<pk>\d+)/aprobar/$', permission_required('mantenimientos.aprobar_mantenimiento')(aprobar_mantenimiento), name='aprobar_mantenimiento'),
	#url(r'^mantenimiento/(?P<pk>\d+)/aprobar_preventivo/$', permission_required('mantenimientos.delete_mantenimiento')(aprobar_mantenimiento_preventivo), name='aprobar_mantenimiento_preventivo'),

	url(r'^$', mantenimientos_presentacion),

]

publico/urls.py
from django.conf.urls import patterns, include, url
from recursos.ajax import *
from recursos.autocomplete import *
from publico.views import *

from django.contrib.auth.decorators import permission_required

urlpatterns = [

    # Views

    url(r'^recurso/(?P<pk>\d+)/detail/$', RecursoPublicoDetailView.as_view(), name='recurso_det'),

    url(r'^recurso/(?P<pk>\d+)/cola/$', ColaRecursoPublicoDetailView.as_view(), name='cola_recurso_det'),

    url(r'^recurso/(?P<pk>\d+)/estadistica/$', EstadisticasRecursoPublicoDetailView.as_view(), name='estadisticas_recurso_det'),


    url(r'^recurso/$', RecursoPublicoListView.as_view(), name='recurso_publico_lis'),
    url(r'^reserva/$', ReservaPublicoListView.as_view(), name='reserva_publico_lis'),

    url(r'^$', publico_presentacion),


]

sigestrec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'sigestrec.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'sigestrec.views.home', name='home'),


    url(r'^admin/reservas/', include('reservas.urls')),
    url(r'^admin/recursos/', include('recursos.urls')),
    url(r'^admin/mantenimientos/', include('mantenimientos.urls')),
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^publico/', include('publico.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

mantenimientos/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
PREVENTIVO = 0
CORRECTIVO = 1
TIPO_MANTENIMIENTO=(
	(PREVENTIVO, "preventivo"),
	(CORRECTIVO, "correctivo")
)

# Create your models here.
class Mantenimiento(models.Model):
	class Meta:
		permissions = (
			("aprobar_mantenimiento", "Puede aprobar un mantenimiento"),
		)
	recurso = models.ForeignKey("recursos.Recurso")
	tipo = models.IntegerField(default = CORRECTIVO, choices=TIPO_MANTENIMIENTO, editable=False)

	responsable = models.CharField(max_length=100, null=True, blank=True)
	costo  = models.CharField(max_length=100, null=True, blank=True)
	fecha_de_devolucion = models.DateField(null=True, blank=True)
	observaciones = models.TextField(max_length=1000, null=True, blank=True)

	fecha = models.DateField(default=date.today, editable=False)
	activo = models.BooleanField(default=True, editable=False)
	


	def __unicode__(self):
		return unicode(self.recurso.nombre)

mantenimientos/forms.py
from dal import autocomplete
from django import forms

from mantenimientos.models import *

class MantenimientoForm(forms.ModelForm):
    """
    Formulario de tipo de recursos con widgets personalizados
    """
    class Meta:
        model = Mantenimiento
        fields = ('__all__')
        widgets = {
            "recurso": autocomplete.ModelSelect2(url='/admin/recursos/recursoautocomplete/'),
        }

mantenimientos/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.db.models import Q

from django.contrib.auth.models import User, Group

from recursos.models import *
from mantenimientos.forms import *

from extra.globals import listview_to_excel

from django.http import Http404
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

def aprobar_mantenimiento(request, pk):
	context = RequestContext(request)
	mantenimiento = Mantenimiento.objects.get(pk=pk)

	if request.method == 'POST':
		mantenimiento.activo = False
		mantenimiento.save()

		recurso = mantenimiento.recurso
		recurso.estado=0 #disponible
		recurso.save()

		return redirect('/admin/mantenimientos/mantenimiento')

	mensaje = "Esta seguro que desea aprobar el mantenimiento?" 

	return render_to_response("admin/confirm.html", {'mensaje': mensaje, 'object':mantenimiento,}, context)




class MantenimientoListView(ListView):
	"""
	View lista de mantenimientos, sobreescribiendo la vista propia del admin
	"""
	model = Mantenimiento
	template_name = "mantenimiento_list.html"

	def get_queryset(self):
		mantenimientos = Mantenimiento.objects.filter(activo=True).order_by('fecha')

		q = self.request.GET.get('q', '')
		if q != '':
			mantenimientos = mantenimientos.filter( Q(recurso__codigo__startswith=q) | Q(recurso__nombre__icontains=q) | Q(recurso__observaciones__icontains=q) )

		tipodemantenimiento = self.request.GET.get('tipodemantenimiento', '')
		if tipodemantenimiento != '':
			mantenimientos = mantenimientos.filter(tipo=int(tipodemantenimiento))

		return mantenimientos

	def render_to_response(self, context, **response_kwargs):
		if 'excel' in self.request.GET.get('excel', ''): 
			lista_datos=[]
			datos = self.get_queryset()
			for dato in datos:
				lista_datos.append([dato.recurso.nombre, dato.get_tipo_display(), dato.fecha.strftime("%Y/%m/%d")])

			titulos=[ 'Recurso','tipo ', 'fecha de mantenimiento' ]
			return listview_to_excel(lista_datos,'Mantenimientos',titulos)
		
		return super(MantenimientoListView, self).render_to_response(context, **response_kwargs)

	def get_context_data(self, **kwargs):
		context = super(MantenimientoListView, self).get_context_data(**kwargs)
		context['q'] = self.request.GET.get('q', '')
		context['tipodemantenimiento'] = self.request.GET.get('tipodemantenimiento', '')

		return context
		
	@method_decorator(staff_member_required)
	def dispatch(self, *args, **kwargs):
		return super(MantenimientoListView, self).dispatch(*args, **kwargs)


class MantenimientoAprobadoListView(MantenimientoListView):
	template_name = "mantenimiento_aprobado_list.html"

	def get_queryset(self):
		mantenimientos = Mantenimiento.objects.filter(activo=False).order_by('fecha')

		q = self.request.GET.get('q', '')
		if q != '':
			mantenimientos = mantenimientos.filter( Q(recurso__codigo__startswith=q) | Q(recurso__nombre__icontains=q) | Q(recurso__observaciones__icontains=q) )

		tipodemantenimiento = self.request.GET.get('tipodemantenimiento', '')
		if tipodemantenimiento != '':
			mantenimientos = mantenimientos.filter(tipo=int(tipodemantenimiento))

		return mantenimientos

@login_required
def mantenimientos_presentacion(request):
	context = RequestContext(request)
	titulo="MANTENIMIENTOS"
	descripcion="."
	return render_to_response('admin/presentacion.html', {'titulo':titulo,'descripcion':descripcion}, context)

mantenimientos/templates/aprobar_mantenimiento_preventivo.html
{% extends "admin/base_site.html" %}
 
{% block content %}
<div>
	<form action="" method="post">{% csrf_token %}
		<div align="center">

			<h2>{{ mensaje }}</h2>
			<br>

			{{ form.as_table }}
			
			<button type="submit" class="btn btn-success">Aceptar</button>
			<button type="button" onclick="window.history.back(); return false;" class="btn btn-danger">Cancelar</button>

		</div>
	</form>
</div>
{% endblock %}

mantenimientos/templates/mantenimiento_aprobado_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}


{% block content %}
    <form class="form" method="get">
        <h1>Lista de Mantenimientos Procesados</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Recurso:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Nombre o codigo.." name="q" value="{{ q }}">
                        </td>


                        <th style="vertical-align:middle">
                            <strong> Tipo de mantenimiento:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select name="tipodemantenimiento" value="{{ tipodemantenimiento }}" onchange="this.form.submit();">
                                <option value=""></option>
                                <option {% if tipodemantenimiento == '0' %} selected {% endif %} value="0">Preventivo</option>
                                <option {% if tipodemantenimiento == '1' %} selected {% endif %} value="1">Correctivo</option>
                            </select>
                        </td>

                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/mantenimientos/mantenimientoaprobado" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>



        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Recurso</th>
                <th>Tipo</th>

                <th>Responsable</th>
                <th>Costo</th>
                <th>Fecha de mantenimiento</th>
                <th>Fecha de devolucion</th>
                <th>Observaciones</th>


            </tr>
            </thead>

            <tbody>
            {% for mantenimiento in object_list %}
                <tr>
                    <td>{{ mantenimiento.recurso }}</td>
                    <td>{{ mantenimiento.get_tipo_display }}</td>

                    <td>{{ mantenimiento.responsable|default:"" }}</td>
                    <td>{{ mantenimiento.costo|default:"" }}</td>

                    <td>{{ mantenimiento.fecha }}</td>
                    <td>{{ mantenimiento.fecha_de_devolucion|default:"" }}</td>
                    <td>{{ mantenimiento.observaciones|default:"" }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/mantenimientos/mantenimientoaprobado/?page={{ page_obj.previous_page_number }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/mantenimientos/mantenimientoaprobado/?page={{ page_obj.previous_page_number }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/mantenimientos/mantenimientoaprobado/?page={{ page }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/mantenimientos/mantenimientoaprobado/?page={{ page_obj.next_page_number }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/mantenimientos/mantenimientoaprobado/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}

mantenimientos/templates/mantenimiento_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Mantenimientos</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Recurso:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Nombre o codigo.." name="q" value="{{ q }}">
                        </td>


                        <th style="vertical-align:middle">
                            <strong> Tipo de mantenimiento:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select name="tipodemantenimiento" value="{{ tipodemantenimiento }}" onchange="this.form.submit();">
                                <option value=""></option>
                                <option {% if tipodemantenimiento == '0' %} selected {% endif %} value="0">Preventivo</option>
                                <option {% if tipodemantenimiento == '1' %} selected {% endif %} value="1">Correctivo</option>
                            </select>
                        </td>

                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/mantenimientos/mantenimiento" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>

            {% if perms.mantenimientos.add_mantenimiento %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/mantenimientos/mantenimiento/add/';" title="Agregar Mantenimiento">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Recurso</th>
                <th>Tipo</th>

                <th>Fecha de mantenimiento</th>

                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for mantenimiento in object_list %}
                <tr>
                    <td>{{ mantenimiento.recurso }}</td>
                    <td>{{ mantenimiento.get_tipo_display }}</td>

                    <td>{{ mantenimiento.fecha }}</td>

                    <td>
                        {% if perms.mantenimientos.change_mantenimiento %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/mantenimientos/mantenimiento/{{ mantenimiento.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.mantenimientos.delete_mantenimiento %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/mantenimientos/mantenimiento/{{ mantenimiento.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}

                        <!--
                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/mantenimientos/mantenimiento/{{ mantenimiento.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>
                        -->


                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/mantenimientos/mantenimiento/?page={{ page_obj.previous_page_number }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/mantenimientos/mantenimiento/?page={{ page_obj.previous_page_number }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/mantenimientos/mantenimiento/?page={{ page }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/mantenimientos/mantenimiento/?page={{ page_obj.next_page_number }}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/mantenimientos/mantenimiento/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&tipodemantenimiento={{ tipodemantenimiento }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}