publico/urls.py
from django.conf.urls import patterns, include, url
from recursos.ajax import *
from recursos.autocomplete import *
from publico.views import *

from django.contrib.auth.decorators import permission_required

urlpatterns = [

    # Views

    url(r'^recurso/(?P<pk>\d+)/detail/$', RecursoPublicoDetailView.as_view(), name='recurso_det'),

    url(r'^recurso/(?P<pk>\d+)/cola/$', ColaRecursoPublicoDetailView.as_view(), name='cola_recurso_det'),

    url(r'^recurso/(?P<pk>\d+)/estadistica/$', EstadisticasRecursoPublicoDetailView.as_view(), name='estadisticas_recurso_det'),


    url(r'^recurso/$', RecursoPublicoListView.as_view(), name='recurso_publico_lis'),
    url(r'^reserva/$', ReservaPublicoListView.as_view(), name='reserva_publico_lis'),

    url(r'^$', publico_presentacion),


]

recursos/urls.py
from django.conf.urls import patterns, include, url
from recursos.ajax import *
from recursos.autocomplete import *
from recursos.views import *

from django.contrib.auth.decorators import permission_required

urlpatterns = [
	# Autocomplete
    url(
        'caracteristicaautocomplete/$',
       CaracteristicaAutocomplete.as_view(),
        name='caracteristica-autocomplete',
    ),

    url(
        'encargadoderecursoautocomplete/$',
        EncargadoDeRecursoAutocomplete.as_view(),
        name='encargadoderecurso-autocomplete',
    ),

    url(
        'recursoautocomplete/$',
        RecursoAutocomplete.as_view(),
        name='recurso-autocomplete',
    ),

    # Ajax
    url('get_caracteristicas_tipo_de_recurso/$', get_caracteristicas_tipo_de_recurso),

    # Views
    url(r'^tipoderecurso/$', TipoDeRecursoListView.as_view(), name='tipoderecurso_lis'),

    url(r'^recurso/(?P<pk>\d+)/detail/$', RecursoDetailView.as_view(), name='recurso_det'),
    url(r'^recurso/$', RecursoListView.as_view(), name='recurso_lis'),


    url(r'^$', recursos_presentacion),

]

sigestrec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'sigestrec.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'sigestrec.views.home', name='home'),


    url(r'^admin/reservas/', include('reservas.urls')),
    url(r'^admin/recursos/', include('recursos.urls')),
    url(r'^admin/mantenimientos/', include('mantenimientos.urls')),
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^publico/', include('publico.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

recursos/models.py
from django.db import models
from mantenimientos.models import *
from django.contrib.auth.models import User
from reservas.models import *

# Create your models here.
class Caracteristica(models.Model):
    """ 
    Modelo que implementa caracteristicas de la plantilla de los tipos de recursos
    """
    descripcion = models.CharField(max_length=100)

    def __unicode__(self):
        return unicode(self.descripcion)


class TipoDeRecurso(models.Model):
    """ 
    Modelo que implementa tipos de recursos para la clasificacion en recursos
    """
    nombre = models.CharField(max_length=100)
    encargado = models.ForeignKey(User, null=True, blank=False, verbose_name="Encargado del recurso")
    caracteristicas = models.ManyToManyField(Caracteristica, null=True, blank=True)

    def __unicode__(self):
        return unicode(self.nombre)

DISPONIBLE = 0
RESERVADO = 1
EN_MANTENIMIENTO = 2
EN_USO = 3
ESTADO_RECURSO = (
    (DISPONIBLE, 'disponible'),
    (RESERVADO, 'reservado'),
    (EN_MANTENIMIENTO, 'en mantenimiento'),
    (EN_USO, 'en uso')
)

class Recurso(models.Model):
    """
    Modelo que implementa la definicion de un recurso
    """

    codigo = models.CharField(max_length=100, unique=True)
    nombre = models.CharField(max_length=100)
    tipo = models.ForeignKey("TipoDeRecurso")
    observaciones = models.TextField(max_length=1000, null=True, blank=True)
    mantenimiento_preventivo = models.IntegerField(default=0, verbose_name="Mantenimiento preventido (dias)")
    estado = models.IntegerField(default=DISPONIBLE, editable=False, choices=ESTADO_RECURSO)
    creado = models.DateTimeField(auto_now_add=True)
    borrado = models.BooleanField(default=False, editable=False)

    def __unicode__(self):
        return unicode(self.nombre)

    def get_adjudicado(self):
        las_reservas = Reserva.objects.filter(recurso_id=self.id, activo=True).order_by('-fecha', 'hora_inicio', 'grado_prioridad_solicitante')
        print las_reservas
        if las_reservas.count() > 0:
            una_reserva = las_reservas[0]
            return una_reserva.solicitante
        return None


class DetalleDelRecurso(models.Model):
    recurso = models.ForeignKey(Recurso)
    caracteristica = models.ForeignKey(Caracteristica)
    valor = models.CharField(max_length=100, null=True, blank=True)

recursos/forms.py
from dal import autocomplete
from django import forms

from recursos.models import *


class DetalleDelRecursoForm(forms.ModelForm):
    """
    Formulario de detalle de recursos con widgets personalizados
    """
    class Meta:
        model = DetalleDelRecurso
        fields = ('__all__')
        widgets = {
            "caracteristica": autocomplete.ModelSelect2(url='/admin/recursos/caracteristicaautocomplete/'),
        }

class TipoDeRecursoForm(forms.ModelForm):
    """
    Formulario de tipo de recursos con widgets personalizados
    """
    class Meta:
        model = TipoDeRecurso
        fields = ('__all__')
        widgets = {
            "encargado": autocomplete.ModelSelect2(url='/admin/recursos/encargadoderecursoautocomplete/'),
        }

recursos/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.db.models import Q

from django.contrib.auth.models import User, Group

from recursos.models import *
from extra.globals import listview_to_excel

from django.http import Http404
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
#from common.jasper import reportes
class TipoDeRecursoListView(ListView):
	"""
	View lista de tipos de recurso, sobreescribiendo la vista propia del admin
	"""
	model = TipoDeRecurso
	template_name = "tipoderecurso_list.html"

	def get_queryset(self):
		tipos_de_recurso = TipoDeRecurso.objects.all()

		q = self.request.GET.get('q', '')
		if q != '':
			tipos_de_recurso = tipos_de_recurso.filter( nombre__icontains=q )

		return tipos_de_recurso

	def render_to_response(self, context, **response_kwargs):
		if 'excel' in self.request.GET.get('excel', ''): 
			lista_datos=[]
			datos = self.get_queryset()
			for dato in datos:
				lista_datos.append([dato.nombre])

			titulos=[ 'Nombre' ]
			return listview_to_excel(lista_datos,'Tipos de recursos',titulos)
		
		return super(TipoDeRecursoListView, self).render_to_response(context, **response_kwargs)

	def get_context_data(self, **kwargs):
		context = super(TipoDeRecursoListView, self).get_context_data(**kwargs)
		context['q'] = self.request.GET.get('q', '')
		return context

	@method_decorator(staff_member_required)
	def dispatch(self, *args, **kwargs):
		return super(TipoDeRecursoListView, self).dispatch(*args, **kwargs)

class RecursoListView(ListView):
	"""
	View lista de recursos, sobreescribiendo la vista propia del admin
	"""
	model = Recurso
	template_name = "recurso_list.html"

	def get_queryset(self):
		recursos = Recurso.objects.all()

		q = self.request.GET.get('q', '')
		if q != '':
			recursos = recursos.filter( Q(codigo__startswith=q) | Q(nombre__icontains=q) | Q(observaciones__icontains=q) )

		tipoderecurso_id = self.request.GET.get('tipoderecurso_id', '')
		if tipoderecurso_id != '':
			recursos = recursos.filter(tipo_id=tipoderecurso_id)

		encargado_id = self.request.GET.get('encargado_id', '')
		if encargado_id != '':
			recursos = recursos.filter(tipo__encargado_id=encargado_id)

		estado = self.request.GET.get('estado', 'TODOS')
		if estado == 'DISPONIBLE':
			recursos = recursos.filter(estado=0)
		elif estado == 'MANTENIMIENTO':
			recursos = recursos.filter(estado=1)
		elif estado == 'RESERVADO':
			recursos = recursos.filter(estado=2)
		elif estado == 'EN_USO':
			recursos = recursos.filter(estado=3)

		return recursos

	def render_to_response(self, context, **response_kwargs):
		if 'excel' in self.request.GET.get('excel', ''): 
			lista_datos=[]
			datos = self.get_queryset()
			for dato in datos:
				lista_datos.append([dato.codigo, dato.nombre, dato.tipo.nombre, dato.tipo.encargado.get_full_name(), dato.get_estado_display()])

			titulos=[ 'Codigo','Nombre', 'Tipo','Encargado','Estado' ]
			return listview_to_excel(lista_datos,'Recursos',titulos)
		
		return super(RecursoListView, self).render_to_response(context, **response_kwargs)

	def get_context_data(self, **kwargs):
		context = super(RecursoListView, self).get_context_data(**kwargs)
		context['q'] = self.request.GET.get('q', '')
		context['tiposderecurso'] = TipoDeRecurso.objects.all()
		context['tipoderecurso_id'] = int(self.request.GET.get('tipoderecurso_id','')) if (self.request.GET.get('tipoderecurso_id','') != '') else ''

		context['encargados'] = User.objects.filter(groups__name='Encargado de recursos')
		context['encargado_id'] = int(self.request.GET.get('encargado_id', '')) if (self.request.GET.get('encargado_id', '') != '') else ''

		context['estado'] = self.request.GET.get('estado', 'TODOS')

		return context
		
	@method_decorator(staff_member_required)
	def dispatch(self, *args, **kwargs):
		return super(RecursoListView, self).dispatch(*args, **kwargs)

class RecursoDetailView(DetailView):
	model = Recurso
	template_name = "recurso_detail.html"

	@method_decorator(staff_member_required)
	def dispatch(self, *args, **kwargs):
		return super(RecursoDetailView, self).dispatch(*args, **kwargs)

@login_required
def recursos_presentacion(request):
	context = RequestContext(request)
	titulo="RECURSOS"
	descripcion="."
	return render_to_response('admin/presentacion.html', {'titulo':titulo,'descripcion':descripcion}, context)

recursos/templates/recurso_detail.html
{% extends "admin/base_site.html" %}
{% load humanize %}

{% block content %}
<h1>Datos del Material</h1>
<table class="table table-striped table-filter" summary="Datos del Material.">
	<tbody>
		<tr>
			<th scope="row"> Descripcion </th>
			<td> {{ object.descripcion }} </td>
		</tr>
		<tr>
			<th scope="row"> Codigo </th>
			<td> {{ object.id }} </td>
		</tr>

		<tr>
			<th scope="row"> Unidad de Medida </th>
			<td> {{ object.unidad_de_medida }} </td>
		</tr>

		<tr>
			<th scope="row"> Categoria </th>
			<td> {{ object.categoria }} </td>
		</tr>

		<tr>
			<th scope="row"> Stock Actual </th>
			<td> {{ object.stock_actual|floatformat:"2"|intcomma|default_if_none:"&nbsp;" }} </td>
		</tr>

		<tr>
			<th scope="row"> Costo Actual </th>
			<td> {{ object.costo_actual|floatformat:"2"|intcomma|default_if_none:"&nbsp;" }} </td>
		</tr>

		<tr>
			<th scope="row"> Retiro en OT </th>
			<td><input checked={% if object.retiro_ot %}"checked"{% endif %} id="id_retiro_ot" name="retiro_ot" type="checkbox" disabled="disabled"></td>
		</tr>

	</tbody>
</table>


<button type="button" class="btn btn-primary" onclick="window.history.back(); return false;">Volver</button>

{% endblock %}

recursos/templates/recurso_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Recursos</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Buscar:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Nombre o codigo.." name="q" value="{{ q }}">
                        </td>


                        <th style="vertical-align:middle">
                            <strong> Tipo de recurso:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un tipo de recurso.." name="tipoderecurso_id" value="{{ tipoderecurso_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for tipoderecurso in tiposderecurso %}
                                    <option {% if tipoderecurso.pk == tipoderecurso_id %} selected {% endif %} value="{{ tipoderecurso.id }}">{{ tipoderecurso }}</option>
                                {% endfor %}
                            </select>
                        </td>

                    </tr>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Encargado:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un tipo de recurso.." name="encargado_id" value="{{ encargado_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for encargado in encargados %}
                                    <option {% if encargado.pk == encargado_id %} selected {% endif %} value="{{ encargado.id }}">{{ encargado }}</option>
                                {% endfor %}
                            </select>
                        </td>



                        <th style="vertical-align:middle">
                            <strong> Estado:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select name="estado" value="{{ estado }}" onchange="this.form.submit();">

                                <option {% if 'TODOS' in estado %} selected {% endif %} value="TODOS">----------</option>
                                <option {% if 'DISPONIBLE' in estado %} selected {% endif %} value="DISPONIBLE">DISPONIBLE</option>
                                <option {% if 'RESERVADO' in estado %} selected {% endif %} value="RESERVADO">RESERVADO</option>
                                <option {% if 'MANTENIMIENTO' in entregado %} selected {% endif %} value="MANTENIMIENTO">MANTENIMIENTO</option>
                                <option {% if 'EN_USO' in entregado %} selected {% endif %} value="EN_USO">EN USO</option>
                            </select>
                        </td>





                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/recursos/recurso" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>

            {% if perms.recursos.add_recurso %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/recursos/recurso/add/';" title="Agregar Recurso">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Tipo</th>

                <th>Encargado</th>

                <th>Fecha de creacion</th>
                <th>Mantenimiento preventivo (dias)</th>

                <th>Estado</th>
                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for recurso in object_list %}
                <tr>
                    <td>{{ recurso.codigo }}</td>
                    <td>{{ recurso.nombre}}</td>
                    <td>{{ recurso.tipo}}</td>
                    <td>{{ recurso.tipo.encargado }}</td>

                    <td>{{ recurso.creado }}</td>
                    <td>{{ recurso.mantenimiento_preventivo }}</td>

                    <td>{{ recurso.get_estado_display }}</td>
                    <td>
                        {% if perms.recursos.change_recurso %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/recursos/recurso/{{ recurso.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.recursos.delete_recurso %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/recursos/recurso/{{ recurso.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}



                        <!--
                        <button type="button" class="btn btn-info btn-xs" onclick="location.href='/admin/recursos/recurso/{{ recurso.id }}/detail/';" title="Detalle">
                            <i class="fa fa-list-ol"></i>
                        </button>
                        -->


                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/recursos/recurso/?page={{ page_obj.previous_page_number }}&q={{ q }}&tipoderecurso_id={{ tipoderecurso_id }}&encargado_id={{ encargado_id }}&estado={{ estado }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/recursos/recurso/?page={{ page_obj.previous_page_number }}&q={{ q }}&tipoderecurso_id={{ tipoderecurso_id }}&encargado_id={{ encargado_id }}&estado={{ estado }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/recursos/recurso/?page={{ page }}&q={{ q }}&tipoderecurso_id={{ tipoderecurso_id }}&encargado_id={{ encargado_id }}&estado={{ estado }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/recursos/recurso/?page={{ page_obj.next_page_number }}&q={{ q }}&tipoderecurso_id={{ tipoderecurso_id }}&encargado_id={{ encargado_id }}&estado={{ estado }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/recursos/recurso/?page={{ page_obj.paginator.num_pages}}&q={{ q }}&tipoderecurso_id={{ tipoderecurso_id }}&encargado_id={{ encargado_id }}&estado={{ estado }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}

recursos/templates/reporte_recursos.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block content %}
    <form class="form" method="get">
        <h1>Generar reporte de recursos</h1>
     </form>
{% endblock %}

recursos/templates/tipoderecurso_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}



{% block content %}
    <form class="form" method="get">
        <h1>Lista de Tipos de recursos</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>
                        <th style="vertical-align:middle">
                            <strong> Buscar:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <input type="text" class="search-query" placeholder="Nombre.." name="q" value="{{ q }}">
                        </td>


                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/recursos/tipoderecurso" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">

            <button onclick="this.form.submit();" class="btn btn-success" name="excel" value="excel" type="submit" title="Exportar a Excel">
                <i class="fa fa-file-excel-o"></i>
            </button>

            {% if perms.recursos.add_recurso %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/recursos/tipoderecurso/add/';" title="Agregar tipo de recurso">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for tipoderecurso in object_list %}
                <tr>
                    <td>{{ tipoderecurso.nombre}}</td>

                    <td>
                        {% if perms.recursos.change_tipoderecurso %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/recursos/tipoderecurso/{{ tipoderecurso.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.recursos.delete_tipoderecurso %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/recursos/tipoderecurso/{{ tipoderecurso.id }}/delete/';" title="Borrar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/recursos/tipoderecurso/?page={{ page_obj.previous_page_number }}&q={{ q }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/recursos/tipoderecurso/?page={{ page_obj.previous_page_number }}&q={{ q }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/recursos/tipoderecurso/?page={{ page }}&q={{ q }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/recursos/tipoderecurso/?page={{ page_obj.next_page_number }}&q={{ q }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/recursos/tipoderecurso/?page={{ page_obj.paginator.num_pages}}&q={{ q }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}