publico/urls.py
from django.conf.urls import patterns, include, url
from recursos.ajax import *
from recursos.autocomplete import *
from publico.views import *

from django.contrib.auth.decorators import permission_required

urlpatterns = [

    # Views

    url(r'^recurso/(?P<pk>\d+)/detail/$', RecursoPublicoDetailView.as_view(), name='recurso_det'),

    url(r'^recurso/(?P<pk>\d+)/cola/$', ColaRecursoPublicoDetailView.as_view(), name='cola_recurso_det'),

    url(r'^recurso/(?P<pk>\d+)/estadistica/$', EstadisticasRecursoPublicoDetailView.as_view(), name='estadisticas_recurso_det'),


    url(r'^recurso/$', RecursoPublicoListView.as_view(), name='recurso_publico_lis'),
    url(r'^reserva/$', ReservaPublicoListView.as_view(), name='reserva_publico_lis'),

    url(r'^$', publico_presentacion),


]

reservas/urls.py
from django.conf.urls import patterns, include, url
from reservas.autocomplete import *
from reservas.views import *
from reservas.reports import *

from django.contrib.auth.decorators import permission_required

urlpatterns = [
	# Autocomplete


    url(
        r'^reservarecursoautocomplete/$',
        ReservaRecursoAutocomplete.as_view(),
        name='reservarecurso-autocomplete',
    ),


    url(
        r'^reservarecursogeneralautocomplete/$',
        ReservaRecursoGeneralAutocomplete.as_view(),
        name='reservarecursogeneral-autocomplete',
    ),

    # Views
    url(r'^reserva/$', ReservaListView.as_view(), name='reserva_lis'),
    url(r'^mireserva/$', MiReservaListView.as_view(), name='mireserva_lis'),
    url(r'^mireserva/(?P<pk>\d+)/cancelar/$', permission_required('reservas.cancelar_reserva')(cancelar_mireserva), name='cancelar_mireserva'),

    url(r'^reserva/(?P<pk>\d+)/entregargeneral/$', permission_required('reservas.entregar_recurso')(EntregarRecursoGeneralUpdateView.as_view()), name='entregar_recurso_general'),
    url(r'^reserva/(?P<pk>\d+)/entregarespecifico/$', permission_required('reservas.entregar_recurso')(entregar_recurso_especifico), name='entregar_recurso_especifico'),
    url(r'^reserva/(?P<pk>\d+)/entregar/$', permission_required('reservas.entregar_recurso')(entregar_recurso), name='entregar_recurso'),
    url(r'^reserva/(?P<pk>\d+)/recibir/$', permission_required('reservas.recibir_recurso')(recibir_recurso), name='recibir_recurso'),
    url(r'^reserva/(?P<pk>\d+)/cancelar/$', permission_required('reservas.cancelar_reserva')(cancelar_reserva), name='cancelar_reserva'),
    url(r'^reserva/(?P<pk>\d+)/delete/$', permission_required('reservas.cancelar_reserva')(cancelar_reserva), name='cancelar_reserva'),

    url(r'^reserva/(?P<pk>\d+)/print_entrega/$', permission_required('reservas.imprimir_comprobante')(reporte_entrega_recurso), name='reporte_entrega_recurso'),
    url(r'^reserva/(?P<pk>\d+)/print_devolucion/$', permission_required('reservas.imprimir_comprobante')(reporte_devolucion_recurso), name='reporte_devolucion_recurso'),

    url(r'^$', reservas_presentacion),

]

sigestrec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'sigestrec.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'sigestrec.views.home', name='home'),


    url(r'^admin/reservas/', include('reservas.urls')),
    url(r'^admin/recursos/', include('recursos.urls')),
    url(r'^admin/mantenimientos/', include('mantenimientos.urls')),
    url(r'^admin/auth/', include('sistema.urls')),
    url(r'^admin/sistema/', include('sistema.urls')),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^publico/', include('publico.urls')),

    url(r'^admin/', include(admin.site.urls)),
]

reservas/models.py
from django.db import models
from mantenimientos.models import *
from django.contrib.auth.models import User
from datetime import datetime, date, time
# Create your models here.

BOOLEANO =( (True, 'SI'), (False,'NO') )


HORAS_RESERVA =(
    (time(6,0,0), '6:00'),
    (time(6,30,0), '6:30'),

    (time(7,0,0), '7:00'),
    (time(7,30,0), '7:30'),

    (time(8,0,0), '8:00'),
    (time(8,30,0), '8:30'),

    (time(9,0,0), '9:00'),
    (time(9,30,0), '9:30'),

    (time(10,0,0), '10:00'),
    (time(10,30,0), '10:30'),

    (time(11,0,0), '11:00'),
    (time(11,30,0), '11:30'),

    (time(12,0,0), '12:00'),
    (time(12,30,0), '12:30'),

    (time(13,0,0), '13:00'),
    (time(13,30,0), '13:30'),

    (time(14,0,0), '14:00'),
    (time(14,30,0), '14:30'),

    (time(15,0,0), '15:00'),
    (time(15,30,0), '15:30'),

    (time(16,0,0), '16:00'),
    (time(16,30,0), '16:30'),

    (time(17,0,0), '17:00'),
    (time(17,30,0), '17:30'),

    (time(18,0,0), '18:00'),
    (time(18,30,0), '18:30'),

    (time(19,0,0), '19:00'),
    (time(19,30,0), '19:30'),

    (time(20,0,0), '20:00'),
    (time(20,30,0), '20:30'),

    (time(21,0,0), '21:00'),
    (time(21,30,0), '21:30'),

    (time(22,0,0), '22:00'),
    (time(22,30,0), '22:30'),

    (time(23,0,0), '23:00'),
    (time(23,30,0), '23:30')

    )


class Reserva(models.Model):
    """ 
    Modelo que implementa reservas de recursos
    """
    class Meta:
        permissions = (
            ("cancelar_reserva", "Puede cancelar la reserva"),
            ("entregar_recurso", "Puede entregar el recurso"),
            ("recibir_recurso", "Puede recibir el recurso"),
            ("imprimir_comprobante", "Puede imprimir comprobante"),

        )

    tipo_recurso = models.ForeignKey('recursos.TipoDeRecurso')
    recurso = models.ForeignKey('recursos.Recurso', null=True, blank=True)
    solicitante = models.ForeignKey(User)
    fecha = models.DateField(default=date.today, editable=False)
    hora_inicio = models.TimeField(choices=HORAS_RESERVA)
    hora_fin = models.TimeField(choices=HORAS_RESERVA)
    activo = models.BooleanField(default=True, editable=False, choices=BOOLEANO)
    cancelado = models.BooleanField(default=False, editable=False,choices=BOOLEANO)
    entregado = models.BooleanField(default=False, editable=False, choices=BOOLEANO)
    devuelto = models.BooleanField(default=False, editable=False, choices=BOOLEANO)
    creado = models.DateTimeField(auto_now_add=True)
    grado_prioridad_solicitante = models.IntegerField(default=0, editable=False)

    fecha_hora_entrega = models.DateTimeField(null=True, blank=True, editable=False)
    fecha_hora_devolucion = models.DateTimeField(null=True, blank=True, editable=False)
    fecha_hora_cancelacion = models.DateTimeField(null=True, blank=True, editable=False)

    notificacion_enviada = models.BooleanField(default=False, editable=False, choices=BOOLEANO)


    def __unicode__(self):
        return unicode(self.id)

    def posicion_en_cola(self):
        pass


class MiReserva(Reserva):
    class Meta:
        proxy = True

reservas/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import UpdateView
from django.db.models import Q

from django.contrib.auth.models import User, Group

from reservas.models import *
from reservas.forms import *

from recursos.models import *

from extra.globals import listview_to_excel

from django.http import Http404
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required

from datetime import datetime	


from django.core.mail import EmailMessage

def enviar_notificacion(asunto, mensaje, destinatario):
	email = EmailMessage(asunto, mensaje, to=[destinatario.email])
	email.send()

def get_estado_recurso(recurso):
	reservas = Reserva.objects.filter(recurso_id = recurso.id, activo = True)
	if(reservas.count() > 0):
		return 1 #disponible
	return 0 #reservado

def entregar_recurso(request, pk):
	context = RequestContext(request)
	reserva = Reserva.objects.get(pk=pk)

	if reserva.recurso == None:
		return redirect('/admin/reservas/reserva/'+str(pk)+'/entregargeneral')	
	
	return redirect('/admin/reservas/reserva/'+str(pk)+'/entregarespecifico')	


class EntregarRecursoGeneralUpdateView(UpdateView):
	model = Reserva
	form_class = EntregarRecursoGeneralForm
	template_name = 'entregar_recuso_general_form.html'
	success_url= '/admin/reservas/reserva'



def entregar_recurso_especifico(request, pk):
	context = RequestContext(request)
	reserva = Reserva.objects.get(pk=pk)

	if request.method == 'POST':
		reserva.entregado = True
		reserva.fecha_hora_entrega = datetime.now()
		reserva.save()

		recurso = reserva.recurso
		recurso.estado = 3 #en uso
		recurso.save()

		reservas = Reserva.objects.filter(recurso_id=recurso.id, hora_inicio__lte=reserva.hora_fin, fecha=reserva.fecha).exclude(id=reserva.id)
		for una_reserva in reservas:
			una_reserva.activo=False
			una_reserva.cancelado=True
			una_reserva.fecha_hora_cancelacion = datetime.now()
			una_reserva.save()

		return redirect('/admin/reservas/reserva')

	mensaje = "Esta seguro que desea entragar el recurso?" 

	return render_to_response("admin/confirm.html", {'mensaje': mensaje, 'object':reserva,}, context)



def recibir_recurso(request, pk):
	context = RequestContext(request)
	reserva = Reserva.objects.get(pk=pk)

	if request.method == 'POST':
		reserva.devuelto = True
		reserva.fecha_hora_devolucion = datetime.now()
		reserva.activo=False
		reserva.save()

		recurso = reserva.recurso
		recurso.estado = get_estado_recurso(recurso) # disponible o reservado
		recurso.save()

		return redirect('/admin/reservas/reserva')

	mensaje = "Esta seguro que desea recibir el recurso?" 

	return render_to_response("admin/confirm.html", {'mensaje': mensaje, 'object':reserva,}, context)


def cancelar_reserva(request, pk):
	context = RequestContext(request)
	reserva = Reserva.objects.get(pk=pk)

	if request.method == 'POST':
		reserva.cancelado = True
		reserva.fecha_hora_cancelacion = datetime.now()
		reserva.activo=False
		reserva.save()

		recurso = reserva.recurso
		if recurso != None:
			recurso.estado = get_estado_recurso(recurso) # disponible o reservado
			recurso.save()

		enviar_notificacion(
			asunto="Cancelacion de reserva",
			mensaje="Su reserva del recurso " + reserva.recurso.nombre + " fue cancelada",
			destinatario=reserva.solicitante
		)

		return redirect('/admin/reservas/reserva')

	mensaje = "Esta seguro que desea cancelar la reserva?" 

	return render_to_response("admin/confirm.html", {'mensaje': mensaje, 'object':reserva,}, context)



def cancelar_mireserva(request, pk):
	context = RequestContext(request)
	reserva = Reserva.objects.get(pk=pk)

	if request.method == 'POST':
		reserva.cancelado = True
		reserva.fecha_hora_cancelacion = datetime.now()
		reserva.activo=False
		reserva.save()

		recurso = reserva.recurso
		if recurso != None:
			recurso.estado = get_estado_recurso(recurso) # disponible o reservado
			recurso.save()

		enviar_notificacion(
			asunto="Cancelacion de reserva",
			mensaje="Usted cancelo su reserva del recurso " + reserva.recurso.nombre,
			destinatario=reserva.solicitante
		)

		return redirect('/admin/reservas/mireserva')

	mensaje = "Esta seguro que desea cancelar la reserva?" 

	return render_to_response("admin/confirm.html", {'mensaje': mensaje, 'object':reserva,}, context)








class ReservaListView(ListView):
	"""
	View lista de reservas, sobreescribiendo la vista propia del admin
	"""
	model = Reserva
	template_name = "reserva_list.html"

	def get_queryset(self):
		reservas = Reserva.objects.all()

		tipoderecurso_id = self.request.GET.get('tipoderecurso_id', '')
		if tipoderecurso_id != '':
			reservas = reservas.filter(tipo_recurso_id=tipoderecurso_id)

		recurso_id = self.request.GET.get('recurso_id', '')
		if recurso_id != '':
			reservas = reservas.filter(recurso_id=recurso_id)

		solicitante_id = self.request.GET.get('solicitante_id', '')
		if solicitante_id != '':
			reservas = reservas.filter(solicitante_id=solicitante_id)


		activo = self.request.GET.get('activo', 'SI')
		if activo == 'SI':
			reservas = reservas.filter(activo=True)
		elif activo == 'NO':
			reservas = reservas.filter(activo=False)

		cancelado = self.request.GET.get('cancelado', 'NO')
		if cancelado == 'SI':
			reservas = reservas.filter(cancelado=True)
		elif cancelado == 'NO':
			reservas = reservas.filter(cancelado=False)

		entregado = self.request.GET.get('entregado', 'TODOS')
		if entregado == 'SI':
			reservas = reservas.filter(entregado=True)
		elif entregado == 'NO':
			reservas = reservas.filter(entregado=False)


		devuelto = self.request.GET.get('devuelto', 'TODOS')
		if devuelto == 'SI':
			reservas = reservas.filter(devuelto=True)
		elif devuelto == 'NO':
			reservas = reservas.filter(devuelto=False)

		return reservas.order_by('-fecha', 'hora_inicio', 'grado_prioridad_solicitante')


	def render_to_response(self, context, **response_kwargs):
		if 'excel' in self.request.GET.get('excel', ''): 
			lista_datos=[]
			datos = self.get_queryset()
			for dato in datos:
				lista_datos.append([
					dato.recurso.codigo,
					dato.recurso.nombre,
					dato.recurso.tipo.nombre,
					dato.recurso.tipo.encargado.get_full_name(),
					dato.recurso.get_estado_display(),
					dato.fecha.strftime("%d/%m/%Y"),
					dato.solicitante.get_full_name(),
					dato.get_activo_display()

				])

			titulos=[ 'Codigo','Recurso', 'Tipo de recurso', 'Encargado', 'Estado del recurso', 'fecha reserva', 'Solicitante', 'Activo' ]
			return listview_to_excel(lista_datos,'Reservas',titulos)
		
		return super(ReservaListView, self).render_to_response(context, **response_kwargs)


	def get_context_data(self, **kwargs):
		context = super(ReservaListView, self).get_context_data(**kwargs)

		context['tiposderecurso'] = TipoDeRecurso.objects.all()
		context['tipoderecurso_id'] = int(self.request.GET.get('tipoderecurso_id','')) if (self.request.GET.get('tipoderecurso_id','') != '') else ''

		context['recursos'] = Recurso.objects.filter(borrado=False)
		context['recurso_id'] = int(self.request.GET.get('recurso_id','')) if (self.request.GET.get('recurso_id','') != '') else ''

		context['solicitantes'] = User.objects.all()
		context['solicitante_id'] = int(self.request.GET.get('solicitante_id','')) if (self.request.GET.get('solicitante_id','') != '') else ''

		context['activo'] = self.request.GET.get('activo', 'SI')
		context['cancelado'] = self.request.GET.get('cancelado', 'NO')
		context['entregado'] = self.request.GET.get('entregado', 'TODOS')
		context['devuelto'] = self.request.GET.get('devuelto', 'TODOS')



		return context
		
	@method_decorator(staff_member_required)
	def dispatch(self, *args, **kwargs):
		return super(ReservaListView, self).dispatch(*args, **kwargs)


class MiReservaListView(ListView):
	"""
	View lista de mis reservas, sobreescribiendo la vista propia del admin
	"""
	model = MiReserva
	template_name = "mireserva_list.html"

	def get_queryset(self):
		solicitante = self.request.user
		reservas = MiReserva.objects.filter(solicitante_id=solicitante.id, activo=True)

		tipoderecurso_id = self.request.GET.get('tipoderecurso_id', '')
		if tipoderecurso_id != '':
			reservas = reservas.filter(tipo_recurso_id=tipoderecurso_id)

		recurso_id = self.request.GET.get('recurso_id', '')
		if recurso_id != '':
			reservas = reservas.filter(recurso_id=recurso_id)

		print reservas

		return reservas.order_by('-fecha', 'hora_inicio', 'grado_prioridad_solicitante')


	def get_context_data(self, **kwargs):
		context = super(MiReservaListView, self).get_context_data(**kwargs)

		context['tiposderecurso'] = TipoDeRecurso.objects.all()
		context['tipoderecurso_id'] = int(self.request.GET.get('tipoderecurso_id','')) if (self.request.GET.get('tipoderecurso_id','') != '') else ''

		context['recursos'] = Recurso.objects.filter(borrado=False)
		context['recurso_id'] = int(self.request.GET.get('recurso_id','')) if (self.request.GET.get('recurso_id','') != '') else ''

		return context


@login_required
def reservas_presentacion(request):
	context = RequestContext(request)
	titulo="RESERVAS"
	descripcion="."
	return render_to_response('admin/presentacion.html', {'titulo':titulo,'descripcion':descripcion}, context)

reservas/templates/entregar_recuso_general_form.html
{% extends "admin/base_site.html" %}

{% block content %}
<div>
	<form action="" method="post">{% csrf_token %}
		<div align="center">

			<h2>Esta seguro que desea entragar el recurso?</h2>
			<br>

			{{ form.as_p }}

			<button type="submit" class="btn btn-success">Aceptar</button>
			<button type="button" onclick="window.history.back(); return false;" class="btn btn-danger">Cancelar</button>

		</div>
	</form>
</div>
{% endblock %}

{% block footer %}
{{ form.media }}
{% endblock %}

reservas/templates/mireserva_list.html
{% extends 'admin/base_site.html' %}
{% load humanize %}

{% load i18n admin_static %}
{% load my_tags %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'chosen/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'chosen/docsupport/prism.css' %}">
{% endblock %}

{% block extrajs %}
    <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
    <script src="{% static 'chosen/docsupport/prism.js' %}"></script>

    <script type="text/javascript">
        $(".chosen-select").chosen({
            disable_search_threshold: 0,
            no_results_text: "Sin resultados..",
            width: "300px",
            allow_single_deselect: true
        });
        $('.chosen-select').trigger('chosen:updated');
    </script>
{% endblock %}

{% block content %}
    <form class="form" method="get">
        <h1>Lista de Mis Reservas</h1>
        <center>
            <dl>
                <table class="table-filter table table-bordered table-stripped">
                    <tbody>
                    <tr>


                        <th style="vertical-align:middle">
                            <strong> Tipo de recurso:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un tipo de recurso.." name="tipoderecurso_id" value="{{ tipoderecurso_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for tipoderecurso in tiposderecurso %}
                                    <option {% if tipoderecurso.pk == tipoderecurso_id %} selected {% endif %} value="{{ tipoderecurso.id }}">{{ tipoderecurso }}</option>
                                {% endfor %}
                            </select>
                        </td>



                        <th style="vertical-align:middle">
                            <strong> Recurso:</strong>
                        </th>
                        <td style="vertical-align:middle">
                            <select class="chosen-select" data-placeholder="Seleccione un recurso.." name="recurso_id" value="{{ recurso_id }}" onchange="this.form.submit();">
                                <option value=""></option>
                                {% for recurso in recursos %}
                                    <option {% if recurso.pk == recurso_id %} selected {% endif %} value="{{ recurso.id }}">{{ recurso }}</option>
                                {% endfor %}
                            </select>
                        </td>





                        <th style="border-top :3px solid white; border-right :3px solid white; border-bottom :3px solid white;">
                            <a class="btn btn-info" href="/admin/reservas/mireserva" title="Limpiar Filtros">
                                <i class="fa fa-undo"></i>
                            </a>
                            <input type="submit" value="Buscar" class="btn btn-success" hidden="hidden" style="display: none">
                        </th>
                    </tr>
                    </tbody>
                </table>
            </dl>
        </center>

        <div id="next_button" align="right">



            {% if perms.reservas.add_mireserva %}
                <button type="button" class="btn btn-primary" onclick="location.href='/admin/reservas/mireserva/add/';" title="Agregar Reserva">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            {% endif %}

        </div>
    </form>


    <br/>

    <div align="center">
        <table id="result_list" class="table table-striped table-filter">
            <thead>
            <tr>

                <th>Tipo de Recurso</th>
                <th>Recurso</th>
                <th>Para usarse</th>

                <th>Acciones</th>

            </tr>
            </thead>

            <tbody>
            {% for reserva in object_list %}
                <tr>
                    <td>{{ reserva.tipo_recurso }}</td>
                    <td>{{ reserva.recurso|default_if_none:"&nbsp;" }}</td>

                    <td>{{ reserva.fecha }} ({{ reserva.hora_inicio }} a {{ reserva.hora_fin }}) </td>

                    <td>
                        {% if perms.reservas.change_reserva %}
                            <button type="button" class="btn btn-warning btn-xs" onclick="location.href='/admin/reservas/mireserva/{{ reserva.id }}/';" title="Editar">
                                <i class="fa fa-pencil"></i>
                            </button>
                        {% endif %}

                        {% if perms.reservas.delete_reserva or perms.reservas.cancelar_reserva %}
                            <button type="button" class="btn btn-danger btn-xs" onclick="location.href='/admin/reservas/mireserva/{{ reserva.id }}/cancelar/';" title="Cancelar">
                                <i class="fa fa-minus"></i>
                            </button>
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
        <table class="table">
            <td>
                <center>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="previous">
                                <a href="/admin/reservas/mireserva/?page={{ page_obj.previous_page_number }}&tipoderecurso_id={{ tipoderecurso_id }}&recurso_id={{ recurso_id }}">
                                    <span aria-hidden="true">&larr;</span> Primera
                                </a>
                            </li>

                            <li>
                                <a href="/admin/reservas/mireserva/?page={{ page_obj.previous_page_number }}&tipoderecurso_id={{ tipoderecurso_id }}&recurso_id={{ recurso_id }}">
                                    Anterior
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_obj.paginator.page_range|paginator_delimiter:page_obj.number %}
                            <li>
                                <a {% if page == page_obj.number %} class="active" style="background-color:#DD4814;color:white;" {% endif %} href="/admin/reservas/mireserva/?page={{ page }}&tipoderecurso_id={{ tipoderecurso_id }}&recurso_id={{ recurso_id }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="/admin/reservas/mireserva/?page={{ page_obj.next_page_number }}&tipoderecurso_id={{ tipoderecurso_id }}&recurso_id={{ recurso_id }}">
                                    Siguiente
                                </a>
                            </li>

                            <li class="next">
                                <a href="/admin/reservas/mireserva/?page={{ page_obj.paginator.num_pages}}&tipoderecurso_id={{ tipoderecurso_id }}&recurso_id={{ recurso_id }}">
                                    &Uacute;ltima <span aria-hidden="true">&rarr;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </center>
            </td>
            <th>
                Pag. {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
            </th>
        </table>
    {% endif %}
{% endblock %}